### ISSUE TITLE
Review Step?

### ISSUE THREAD

**Issue by davist11** [digital-pros/commerce-authorize#1]
I'm curious how you would get this to work with a review step and Accept.js. So we have a payment page where you enter the payment information, generate the `token` and `tokenDescriptor`, and pass that data to a "review" step where you actually hit one last confirm purchase button to make the payment.

So the form on my review step has

```
<form method="post">
	<input type="hidden" name="action" value="commerce/payments/pay">
	{{ redirectInput('/account/orders/{number}') }}
	<input type="hidden" name="cancelUrl" value="{{ craft.app.request.url | hash }}">
	<input type="hidden" name="orderEmail" value="{{ cart.email }}">
	{{ csrfInput() }}

	{% if cart.token %}
		<input type="hidden" name="token" value="{{ cart.token }}">
	{% endif %}
	{% if cart.tokenDescriptor %}
		<input type="hidden" name="tokenDescriptor" value="{{ cart.tokenDescriptor }}">
	{% endif %}

	<button type="submit">Place Order</button>
</form>
```

I confirmed that `token` and `tokenDescriptor` have values. Upon submitting this form, I get a error that says **The number parameter is required**

Any thoughts on how to get this to work with a review step?

**Comment by benlobach** [comment]
@davist11, great question! Do you have Accept.js enabled in the plugin settings?

**Comment by davist11** [comment]
Yep, and it's generating the token and descriptor correctly. I'm actually storing the `token` and `tokenDescriptor` on the cart so I can access it on the review page. (I temporarily modified your JS code).

So my payment page looks like

```
<form method="post" id="paymentForm">
	<input type="hidden" name="action" value="commerce/cart/update-cart">
	{{ redirectInput('checkout/review') }}
	{{ csrfInput() }}

	<input type="hidden" name="token" id="token">
	<input type="hidden" name="tokenDescriptor" id="tokenDescriptor">

	<input type="hidden" name="fields[token]" id="cart-token">
	<input type="hidden" name="fields[tokenDescriptor]" id="cart-tokenDescriptor">

	<div class="form">
		[PAYMENT FORM FIELDS]

		{{ cart.gateway.getPaymentFormHtml({})|raw }}
	</div>

	<button
		type="submit"
		class="button -orange"
		id="authorizeSubmit"
		name="authorizeSubmit"
		onclick="event.preventDefault(); sendPaymentDataToAnet();"
	>
		Continue
	</button>
</form>
```

Then I modified your JS to add:

```
function paymentFormUpdate(opaqueData) {
    ...
    document.getElementById("cart-token").value = opaqueData.dataValue;
    document.getElementById("cart-tokenDescriptor").value = opaqueData.dataDescriptor;
    ...
}
```

And then finally the review step has the final form

```
<form method="post">
	<input type="hidden" name="action" value="commerce/payments/pay">
	{{ redirectInput('/account/orders/{number}') }}
	<input type="hidden" name="cancelUrl" value="{{ craft.app.request.url | hash }}">
	<input type="hidden" name="orderEmail" value="{{ cart.email }}">
	{{ csrfInput() }}

	{% if cart.token %}
		<input type="hidden" name="token" value="{{ cart.token }}">
	{% endif %}
	{% if cart.tokenDescriptor %}
		<input type="hidden" name="tokenDescriptor" value="{{ cart.tokenDescriptor }}">
	{% endif %}

	<button type="submit">Place Order</button>
</form>
```

So the `token` and `tokenDescriptor` fields are being passed correctly to the `commerce/payments/pay` action.

**Comment by benlobach** [comment]
Thanks, that's super helpful. I probably wouldn't recommend storing the token in the cart/order, but as long as the credit cards field exist and pass validation, the payment should go through. Those details are removed before sending through to the Authorize when Accept.JS is enabled. We'll look into removing that requirement on our end as a feature enhancement.

**Comment by davist11** [comment]
Ok, great! So in terms of expectations about how it would work, would it work like:

- Payment page contains credit card form (including Accept.js)
- Clicking submit on that form would
  - make the JS call to Authorize.net via Accept.js
  - return the token
  - submit the form which calls the `commerce/cart/update-cart` action
  - redirect to review page
- The review page contains a form that upon submit would hit the `commerce/payments/pay` action and finalize the payment

Is that how you see it working?

**Comment by benlobach** [comment]
Yes, that looks correct. Can you post the token directly to the review page without saving it to the cart?

**Comment by davist11** [comment]
I don't think so, since the update cart action redirects based on the `redirectInput` passed in, so it wasn't available in the POST request.

**Comment by benlobach** [comment]
After running testing, you can post directly to the review page (after using Javascript to clear the Credit Card details before the form is submitted), but the final review form does have to present with a valid number in order for the payment to proceed at this point. We're looking into that aspect a bit further.

```
<form method="POST" id="paymentForm" action="/shop/checkout/review">
      {{ csrfInput() }}
</form>
```

**Comment by benlobach** [comment]
@davist11, We released version 1.0.3 this evening which removes the credit card validation when the Accept.js token is present. We're going to close this issue, unless you have an outstanding question?

**Comment by davist11** [comment]
@benlobach I've updated to the latest version, but I'm not seeing any value returned when I output 

`{{ craft.app.request.getBodyParam('token') }}`
or
`{{ craft.app.request.getBodyParam('tokenDescriptor') }}` on the review page

Am I missing something? How are those parameters set when the update cart controller redirects to the redirect input url?

**Comment by benlobach** [comment]
If you would like to use the craft.app.request.getBodyParam functions, you will want to post the form action attribute directly to the review page rather than using the update cart redirect.

**Comment by davist11** [comment]
🤦‍♂️  duh, that makes sense, missed that step. Ok, all set now, thanks for the updates!

Also one minor note you may want to update in the docs. When using Accept.js, your JS requires that the form has the `id="paymentForm"` attribute.

```
document.getElementById("paymentForm").submit();
```
