### ISSUE TITLE
Error when capturing in admin

### ISSUE THREAD

**Issue by keyurshah** [digital-pros/commerce-authorize#11]
**Describe the bug**
I placed an order with paymen type `AUTHORIZE`.

I tried to capture the payment in the admin but got the error:

![image](https://user-images.githubusercontent.com/744385/75400312-bd819d80-58b3-11ea-9b80-0175082a17ea.png)

``` javascript
(USD) (1 USD = 1 USD)"},{"label":"Gateway Response","type":"response","value":"{\"messages\":{\"resultCode\":\"Error\",\"message\":{\"code\":\"E00003\",\"text\":\"The element 'transactionRequest' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'payment' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. List of possible elements expected: 'userFields, surcharge, merchantDescriptor, subMerchant, tip, processingOptions, subsequentAuthInformation, otherTax, shipFrom' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'.\"}}}"}]'> |  
-- | --
```

This does not seem to happen with other gateways.

**To Reproduce**
1. Place order on site with `AUTHORIZE`
2. Go to admin
3. Capture payment.

This is on the latest Craft 3.0.11 and commerce-authorize 1.0.10 versions

Thanks.

**Comment by benlobach** [comment]
@keyurshah, 1.0.11 has been released which fixes this bug. Let me know if you have any questions!

**Comment by keyurshah** [comment]
thanks so much for the quick fix!
