### ISSUE TITLE
Craft 3 cant refund

### ISSUE THREAD

**Issue by bfjare** [digital-pros/commerce-authorize#12]
Craft CMS: 3.4.9
Commerce: 3.0.11
Authorize Gateway: 1.0.11

Getting the error "Couldn’t refund transaction: (Description is required.)"

Adding refund notes and text to the order description field do not solve issue.

**Comment by benlobach** [comment]
Hello, @bfjare! We'd like to dig into this a bit further as we can't replicate the error on our end. Would you mind sharing your Gateway settings and the response from the gateway for this attempted refund?

If you'd rather not post that information here, feel free to email it to hello@digitalpros.co!

**Comment by bfjare** [comment]
Sure thing!
![settings](https://user-images.githubusercontent.com/11744681/76567974-d2f7e980-64a7-11ea-9b97-c93127c08106.png)

**Comment by benlobach** [comment]
Great, thanks! If you click the (i) icon next to the failed refund, can you post/send the results from that area as well?

**Comment by bfjare** [comment]
<img width="1057" alt="Screen Shot 2020-03-12 at 3 37 22 PM" src="https://user-images.githubusercontent.com/11744681/76568865-ae047600-64a9-11ea-8ff0-9e139340ab76.png">
<img width="1386" alt="Screen Shot 2020-03-12 at 3 37 47 PM" src="https://user-images.githubusercontent.com/11744681/76568884-bbb9fb80-64a9-11ea-9c84-17e4b2227fb4.png">

**Comment by benlobach** [comment]
Thanks so much for providing this information! Did your transaction inside Craft Commerce have a billing address associated with the transaction?

**Comment by bfjare** [comment]
<img width="404" alt="Screen Shot 2020-03-13 at 3 34 38 PM" src="https://user-images.githubusercontent.com/11744681/76661100-78778f80-6572-11ea-92b8-795ab19c37b0.png">
 Anyone is welcome to send money to that address.

**Comment by bfjare** [comment]
Remind me to delete these images after we solve this.

**Comment by bfjare** [comment]
<img width="404" alt="Screen Shot 2020-03-13 at 3 34 38 PM" src="https://user-images.githubusercontent.com/11744681/76661227-cab8b080-6572-11ea-999b-6f485b1590ce.png">

**Comment by benlobach** [comment]
You can delete them now, thanks so much! Can you replicate this issue consistently with the same gateway message?

**Comment by bfjare** [comment]
The error message happens on every order yes.

**Comment by benlobach** [comment]
Thanks for giving us some time to look into this issue. We are still unable to replicate the issue on our end. Couple of things to check:

- Has the transaction settled in Authorize.net before attempting the refund? If not, you will need to enable the "Void if Refund Fails" option in the gateway settings.
- In the transaction on your Authorize.net account, is the billing information present on the transaction?
- Does the error still appear on the latest version of Craft Commerce and CraftCMS?

**Comment by benlobach** [comment]
@bfjare - Just wanted to follow-up on this request. Are you still having trouble refunding transactions?

**Comment by bfjare** [comment]
> Has the transaction settled in Authorize.net before attempting the refund? If not, you will need to enable the "Void if Refund Fails" option in the gateway settings.
This ended up being the issue.  Thanks.
