### ISSUE TITLE
Couldn’t capture transaction: (A valid referenced transaction ID is required.) 

### ISSUE THREAD

**Issue by BrandonJamesBorders** [digital-pros/commerce-authorize#13]
**Describe the bug**
When gateway is set to "Authorize Only (Manually Capture)" the order transaction can't be manually captured. Error: Couldn’t capture transaction: (A valid referenced transaction ID is required.)

**To Reproduce**
1. Configure gateway to Authorize Only. Developer Mode enabled. 
2. Create an order (CP or front-end of the website)
3. View order in CP -> Go to Transactions -> Click Capture. 
4. See error: A valid referenced transaction ID is required.

**Expected behavior**
Amount is captured successfully. 

**Screenshots**
```
{
    "refId": "7513",
    "messages": {
        "resultCode": "Error",
        "message": {
            "code": "E00027",
            "text": "The transaction was unsuccessful."
        }
    },
    "transactionResponse": {
        "responseCode": "3",
        "authCode": "000000",
        "avsResultCode": "P",
        "cvvResultCode": {},
        "cavvResultCode": {},
        "transId": "0",
        "refTransID": {},
        "transHash": {},
        "testRequest": "1",
        "accountNumber": {},
        "accountType": {},
        "errors": {
            "error": {
                "errorCode": "33",
                "errorText": "A valid referenced transaction ID is required."
            }
        },
        "transHashSha2": {}
    }
}
```

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 80.0.3987.149

**Additional context**
Craft CMS 3.4.10.1
Authorize.net for Craft Commerce: 1.0.11

**Comment by benlobach** [comment]
Hello @BrandonJamesBorders, are you using Accept.js? Can you paste the result of the initial capture here?

**Comment by BrandonJamesBorders** [comment]
Hey @benlobach. Not using accept.js. Here are my settings:

Developer Mode -> ON
Accept.js -> OFF
Void if Refund Fails -> ON
Insert the Default Form -> ON
Remove CC Database before Submission -> OFF
Saved Payment Sources -> OFF
Enabled for customers to select during checkout? -> ON

Initial Capture: 
```
{
    "refId": "7515",
    "messages": {
        "resultCode": "Ok",
        "message": {
            "code": "I00001",
            "text": "Successful."
        }
    },
    "transactionResponse": {
        "responseCode": "1",
        "authCode": "000000",
        "avsResultCode": "P",
        "cvvResultCode": {},
        "cavvResultCode": {},
        "transId": "0",
        "refTransID": {},
        "transHash": {},
        "testRequest": "1",
        "accountNumber": "XXXX1111",
        "accountType": "Visa",
        "messages": {
            "message": {
                "code": "1",
                "description": "This transaction has been approved."
            }
        },
        "transHashSha2": {}
    }
}
```
Even on a immediate capture transaction, the ID is zero:
![image](https://user-images.githubusercontent.com/6044898/77542056-fcd3e780-6e7b-11ea-99c6-0c07c7b262f9.png)

**Comment by benlobach** [comment]
Just ran a test on this end, and you should be seeing an authorization code. Is your sandbox in live or test mode? What does the transaction look like inside Authorize.net? If you'd rather not share that information there, feel free to send a note to hello@digitalpros.co.

**Comment by BrandonJamesBorders** [comment]
@benlobach Sorry for taking up your time. After testing in test mode, I decided to regenerate my API keys instead of using the ones generated when my account was created. Plugging those keys in and it is working as intended.
