### ISSUE TITLE
Add Config Override Feature

### ISSUE THREAD

**Issue by jlapan** [digital-pros/commerce-authorize#18]
**Is your feature request related to a problem? Please describe.**
Switching between dev/staging and production environments, I have to manually change the "Developer Mode" setting. Sometimes I forget to change it back which will result is payments not being processed.

**Describe the solution you'd like**
It would be great if you could add a config override feature much like how the surprisehighway/craft-avatax plugin does.
https://github.com/surprisehighway/craft-avatax/blob/master/README.md#config-overrides
Craft Documentation: https://docs.craftcms.com/v3/extend/plugin-settings.html#overriding-setting-values

Thanks!

**Comment by benlobach** [comment]
@jlapan, 

Great question! Yes, it is possible to set the gateway settings in a file that can be updated for your various environments. Craft Commerce handles gateway settings a bit differently, and they have a short blurb about it in their [documentation.](https://docs.craftcms.com/commerce/v3/payment-gateways.html#storing-config-outside-of-the-database)

We have a [sample configuration file](https://github.com/digital-pros/commerce-authorize/blob/master/commerce-gateways-sample.php) in the repository. You will need to rename the file (commerce-gateways.php), and place it in the config directory to overwrite the database settings. You will also want to update the handle in the file with the handle that's generated when you create the gateway inside Craft Commerce.

If you have additional questions, let me know! If you'd like to chat about something specific to your setup, feel free to drop us a note at hello@digitalpros.co.
