### ISSUE TITLE
"Invalid OTS token" when saving a payment source using Accept.js

### ISSUE THREAD

**Issue by elivz** [digital-pros/commerce-authorize#19]
**Describe the bug**
When using Accept.js on the front-end and with the `savePaymentSource` option set on the cart, the gateway throws an "Invalid OTS Token" error upon trying to complete the order. I believe this is because the gateway plugin uses the one-time token first to create the saved card in CIM (https://github.com/digital-pros/commerce-authorize/blob/master/src/gateways/Gateway.php#L397) and then uses the same token again to authorize the transaction (https://github.com/digital-pros/commerce-authorize/blob/master/src/gateways/Gateway.php#L178). The second request fails because the token has already been used. 

My understanding is that either the customer payment profile needs to be created in the same request as the payment authorization, or if they are to be two separate steps the second one needs to use the 'customerProfileId' in place of the token. 

**To Reproduce**
1. Enable Accept.js on the front-end
2. Create a test order an enter credit card information at checkout. Select the "Save payment information" checkbox (`<input type="checkbox" name="savePaymentSource" value="1">`).
3. Submit payment form.

**Comment by benlobach** [comment]
Hello @elivz! 

Thanks for filling out an issue!  It doesn't look like we can replicate this error in our clean staging environment, and we haven't seen something like this in the past. 

A couple of quick questions:
- Could you check your network panel and make sure that the form isn't submitting twice for some reason?
- Would you mind installing the default [Craft Commerce Shop templates](https://github.com/craftcms/commerce/tree/develop/example-templates/shop) in a folder on your site and see if you can replicate the error there?

Let me know what you find out and we'll dig a bit deeper, if needed!

**Comment by elivz** [comment]
I tried installing the default templates and comparing the POST data from both versions. After some trial and error, it seems that the transaction fails if there is an `orderNumber` field in the POST data, containing the current cart's number. No idea why...I can't find any place in the code where that would seem to matter. But removing that hidden input has fixed the error.

**Comment by benlobach** [comment]
Thanks for following up with what you found! The additional Order ID was most likely passed all the way to Authorize.net through the Omnipay gateway and Authorize.net didn't know what to do with that information. Let me know if anything else comes up!
