### ISSUE TITLE
Question - use Full Name instead of firstName & lastName

### ISSUE THREAD

**Issue by knynkwl** [digital-pros/commerce-authorize#20]
Is it possible to use just one input field to capture the card holder's name?

**Comment by benlobach** [comment]
Hello, @knynkwl! Authorize.net requires them to be separate fields through the API. One thought or suggestion - you could turn them into hidden fields, and use Javascript to separate them out if you'd like to use one field.

**Comment by knynkwl** [comment]
Ah okay, thanks for the info!
