### ISSUE TITLE
Payment Profiles not Saving to Customer

### ISSUE THREAD

**Issue by bsartain76** [digital-pros/commerce-authorize#22]
Hi,

I’m using the Default Payment Form Code provided in the docs

Enabled Plugin Settings:
Developer Mode
Insert the Default Form
Save Payment Sources

CIM is enabled
This is from Auth.net
========= GENERAL INFORMATION =========
Merchant : Ted Gartain (760083)
Date/Time : 7-Dec-2020 9:39:20 PST

========= ORDER INFORMATION =========
Invoice :
Description : Order #2166
Amount : 29.07 (USD)
Payment Method: MasterCard xxxx9703
Transaction Type: Authorization and Capture

============== Line Items ==============

============== RESULTS ==============
Response : This transaction has been approved.
Auth Code : 4GPCE3
Transaction ID : 40057003926
Address Verification : Street Address: Match -- First 5 Digits of Zip: Match

==== CUSTOMER BILLING INFORMATION ===
Customer ID :
First Name : FName
Last Name : LName
Company : CoCompany
Address : 123 E Grace Street
City : Richmond
State/Province : UT
Zip/Postal Code : 23219
Country : US
Phone : (504) 251-3599
Fax :
E-Mail : fname@gmail.com

==== CUSTOMER SHIPPING INFORMATION ===
First Name : FName
Last Name : LName
Company : CoCompany
Address : 123 E Grace Street
City : Richmond
State/Province : UT
Zip/Postal Code : 23219
Country : US

When I go to CIM within Auth.net and click on the Customer I do not see this Payment being saved.

I guess first, does "Save Payment Profiles" work in Developer Mode?
and second, see the Address Verification: Matched however Customer ID is blank... does that seem correct?

Thanks in advance

**Comment by bsartain76** [comment]
@benlobach sorry as I know this was submitted a few days ago, but any ideas/thoughts here or a possible ETA? Thanks!

**Comment by benlobach** [comment]
@bsartain76, thanks for checking back in! Our team has been running some internal testing and the card should be added to Authorize.net profile, even in development mode. The card you're trying to add wouldn't happen to be on your Craft profile already, would it?

**Comment by bsartain76** [comment]
@benlobach Interesting and thanks! No, there are no cards assigned to the Craft profile I'm using. hmmm, would you mind confirming how the Card get matched to a Profile in Authorize.net. Am I wrong in saying it looks at CustomerID and if nothing then uses the Address to match to a Profile? Thanks!

**Comment by benlobach** [comment]
@bsartain76, would you mind sending a note to hello@digitalpros.co, and maybe we can connect on this further? All of the saved card methods run through the CIM, so you should see a profile with an associated card. Omnipay  handles the account creation and card associating within that account.

We're in the process of working on an update in this area where we're covering some edge cases, and we'd love to investigate what you're seeing.

**Comment by BrandonJamesBorders** [comment]
@benlobach Having issues with this as well. Verified CIM is enabled. Here is our error:

```
2021-01-28 17:06:06 [-][232][-][error][craft\commerce\errors\PaymentSourceException] craft\commerce\errors\PaymentSourceException: Could not create the payment source. in /home/americanlandmastercom/americanlandmaster.com/vendor/craftcms/commerce/src/services/PaymentSources.php:213
Stack trace:
#0 /home/americanlandmastercom/americanlandmaster.com/vendor/craftcms/commerce/src/controllers/PaymentsController.php(258): craft\commerce\services\PaymentSources->createPaymentSource(232, Object(digitalpros\commerce\authorize\gateways\Gateway), Object(digitalpros\commerce\authorize\models\AuthorizePaymentForm))
#1 [internal function]: craft\commerce\controllers\PaymentsController->actionPay()
#2 /home/americanlandmastercom/americanlandmaster.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /home/americanlandmastercom/americanlandmaster.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /home/americanlandmastercom/americanlandmaster.com/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('pay', Array)
#5 /home/americanlandmastercom/americanlandmaster.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('pay', Array)
#6 /home/americanlandmastercom/americanlandmaster.com/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('commerce/paymen...', Array)
#7 /home/americanlandmastercom/americanlandmaster.com/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('commerce/paymen...', Array)
#8 /home/americanlandmastercom/americanlandmaster.com/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /home/americanlandmastercom/americanlandmaster.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /home/americanlandmastercom/americanlandmaster.com/web/index.php(24): yii\base\Application->run()
#11 {main}
2021-01-28 17:05:59 [-][232][-][info][application] $_GET = []
```

**Comment by BrandonJamesBorders** [comment]
Hey @benlobach! 

Any progress/ETA on that update? Thanks!

**Comment by benlobach** [comment]
@BrandonJamesBorders  - Thanks for your patience, sorry for the delay! This should be corrected in the 1.5 release this evening, let me know if you continue to see the problem!

**Comment by BrandonJamesBorders** [comment]
@benlobach Just tested and had the same issue. The site is quite behind now on commerce updates though. Any thoughts on what to look at? 

It works on our local and dev server.

**Comment by benlobach** [comment]
@BrandonJamesBorders - I'd like to run some additional testing here to see if we can track this down.

Is Accept.js enabled in your Gateway settings? After upgrading to 1.5, you don't see the card saved in the Authorize.net CIM?
