### ISSUE TITLE
Craft 4 Compatible - UPDATE: Beta Available

### ISSUE THREAD

**Issue by justinholtweb** [digital-pros/commerce-authorize#27]
**Is your feature request related to a problem? Please describe.**
Craft 4 & Commerce 4  is released but this payment gateway plugin is not currently compatible with Craft 4 or Commerce 4.

**Describe the solution you'd like**
I would like this to be compatible with Craft/Commerce 4.

**Describe alternatives you've considered**
We must use this payment gateway for transactions.

**Additional context**
https://craftcms.com/docs/4.x/

**Comment by benlobach** [comment]
@justinholtweb - Thanks for filling out an issue! We're working on Craft 4 compatibility, but don't have a release date at this moment. We'll update this thread when it's available!

**Comment by justinholtweb** [comment]
Thank you @benlobach I will look forward to your updates when you make progress. Thanks for your work on this.

**Comment by CreateSean** [comment]
Is there an ETA on Craft 4 release?

**Comment by benlobach** [comment]
Thanks for checking in! We've made significant progress, and are currently testing the next version. We hope to have another update within the next week or so.

**Comment by benlobach** [comment]
Hello, Everyone!

The Authorize.net Commerce 4 beta branch is ready to test! We plan to release the develop-v4 branch as the official release in roughly 4 weeks following additional testing from our team, but wanted to make the beta version available for your staging environments ahead of the wide release. You can install the beta version by updating your composer file to use the develop branch, and we've updated the documentation in the "develop-v4"  branch to illustrate any required custom form changes. 

Let us know if you run into any issues as you update the plugin!

### Composer.json Update:

``` "digital-pros/commerce-authorize": "dev-develop-v4", ```

### Custom Form Updates:

> **Note**
> Craft Commerce 4 changed the name and ID attributes on payment fields to include the payment handle (see the code examples below). Sites that use the default form will be updated automatically, but payment forms that use a custom form will need to be updated. Please run test transactions through each Authorize.net gateway after updating to this version. Run into a problem? Open an issue or drop us a note at hello@digitalpros.co.

**Comment by mrbenito** [comment]
> Hello, Everyone!
> 
> The Authorize.net Commerce 4 beta branch is ready to test! We plan to release the develop-v4 branch as the official release in roughly 4 weeks following additional testing from our team, but wanted to make the beta version available for your staging environments ahead of the wide release. You can install the beta version by updating your composer file to use the develop branch, and we've updated the documentation in the "develop-v4" branch to illustrate any required custom form changes.
> 
> Let us know if you run into any issues as you update the plugin!
> 
> ### Composer.json Update:
> `"digital-pros/commerce-authorize": "dev-develop-v4",`
> 
> ### Custom Form Updates:
> > Note
> > Craft Commerce 4 changed the name and ID attributes on payment fields to include the payment handle (see the code examples below). Sites that use the default form will be updated automatically, but payment forms that use a custom form will need to be updated. Please run test transactions through each Authorize.net gateway after updating to this version. Run into a problem? Open an issue or drop us a note at [hello@digitalpros.co](mailto:hello@digitalpros.co).

Hey @benlobach, any update on the timing to release this highly anticipated update for Craft4? Really really appreciate you guys bringing this code in-house!! Thank you @justinholtweb for raising this!

**Comment by CreateSean** [comment]
Really hoping to see this get released soon. It's the only plugin holding back a site update.

**Comment by benlobach** [comment]
@CreateSean, @mrbenito, thanks for your patience! Version 4.0.1 has been released into production!
