### ISSUE TITLE
Undefined currency attribute

### ISSUE THREAD

**Issue by fantasticmachine** [digital-pros/commerce-authorize#29]
Hi, I'm using v1.5.1 of the plugin on a Craft 3 site.
I haven't used Authorize.net so may be missing something here but when I try to put a transaction through I get a response saying the currency attribute is not declared.

This is from the Transaction response
```

{
    "messages": {
        "resultCode": "Error",
        "message": {
            "code": "E00003",
            "text": "The 'CURRENCY' attribute is not declared."
        }
    }
}
```

I can't find reference to this in any documentation. Have you seen this before or have any idea what might be going on?

**Comment by benlobach** [comment]
@fantasticmachine - Great question! We haven't run into this particular error in testing. Is there a currency associated with your cart/order?

**Comment by fantasticmachine** [comment]
@benlobach The post data is as follows, and does include a paymentCurrency

```
$_POST = [
    'action' => 'commerce/payments/pay'
    'redirect' => 'a688f228f82c9469816a6a88d79193197b446c7295c739866af626ffd55d6887https://clientsite.local/admin/commerce/orders/2848467'
    'cancelUrl' => 'a688f228f82c9469816a6a88d79193197b446c7295c739866af626ffd55d6887https://clientsite.local/admin/commerce/orders/2848467'
    'orderNumber' => '108ce1e10c82a8a6424a7adb5f308744'
    'orderEmail' => 'test@mail.com'
    'gatewayId' => '10'
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'firstName' => 'Pete'
    'lastName' => 'Test'
    'number' => '4111111111111111'
    'month' => '12'
    'year' => '2023'
    'cvv' => '900'
    'paymentAmount' => '289.1'
    'paymentCurrency' => 'USD'
]
```

I'm wondering if maybe it's a problem with the plugin and the version of Commerce?
I'm on 1.5.1 of the plugin and using 3.4.10.1 of Commerce

**Comment by benlobach** [comment]
As far as I know, that version should work with Commerce 3.4. Are you using a custom form, or are you using the default form provided by the plugin?

**Comment by benlobach** [comment]
Got it! If we can continue to troubleshoot with the default form, that would be helpful! Is this a new build, or a new issue after updating to 3.4.10.1?

**Comment by fantasticmachine** [comment]
This is a new installation of the plugin on an existing site that has been running 3.4.10 for some time. The client wanted to switch from their current provider to using Authorize.net

I have put the default form in and still no luck. But I think this may be related to settings. Let me fiddle with those and see if I can at least get a failed transaction to show up.

**Comment by fantasticmachine** [comment]
OK. There were other form fields on the page (for other gateways). I have removed those and have switched to using the default form and our own Sandbox account now. However, I'm still getting the currency error.

I also get the same currency attribute error if trying to make a payment in the CP

**Comment by fantasticmachine** [comment]
Have now also tried using customer's own Authorize.net account and get the same error.

I'm wondering if this is something to do with Commerce instead of the gateway since the logs show the following "application" error.

`2022-11-09 05:10:21 [-][1][-][error][application] The 'CURRENCY' attribute is not declared.`

Although the site has been working fine with another credit card payment gateway so I'm not sure why it's not a problem.

**Comment by fantasticmachine** [comment]
Yeah I'm going to set up a clean install I think and try it from there.

I'll also investigate the transaction object to see if the currency is set

**Comment by benlobach** [comment]
@fantasticmachine - Just wanted to check back in here to see how the clean install went?

**Comment by fantasticmachine** [comment]
@benlobach I've been planning to work on this all week and haven't got to it yet. It's on my schedule for tomorrow. I'll let you know what happens!

**Comment by fantasticmachine** [comment]
@benlobach I have finally got around to testing the plugin on a "blank" site and it worked just fine. So the issue is somewhere on this specific site that I'm working on. But as of yet, I have no idea what the problem might be.

**Comment by benlobach** [comment]
@fantasticmachine - that’s interesting! Were you able to check your transaction record for currency values?

**Comment by fantasticmachine** [comment]
@benlobach The transaction record just shows the response above. Further research seems to indicate this is an XML error - Authorize.net cannot parse the XML data it is receiving.

I have tried creating a brand new checkout process using the default templates and still get the same problem. But it still works OK on the "clean" test site that I spun up.

At this point I really don't know what else to look at.

**Comment by fantasticmachine** [comment]
@benlobach the only currency set up is USD. There are no currency settings in the external config - all that is in there is a setting to purge carts.
Other plugins is a good shout. I'll investigate that next

**Comment by fantasticmachine** [comment]
Genius... it was another plugin causing the problem. Either Payflow or Paypal. I disabled them both and now orders go through.

**Comment by benlobach** [comment]
Interesting! Are you actively using that plugin in your installation? Does the issue occur when the plugin is installed, but the gateway is disabled?

**Comment by fantasticmachine** [comment]
I was actually replacing the Payflow payment process with Authorize.net so I can just remove the Payflow gateway. But it was already disabled and I had removed it as a payment option on the front end too. Crazy!
Anyway, it's all working now. Thanks for that spark of inspiration!

**Comment by benlobach** [comment]
That's great news! No problem, we're thankful it's working for you! Thanks for sharing your findings, we'll keep this in mind if it pops up again!
