### ISSUE TITLE
Incorrect class name in Authorize.net PHP SDK causes error when viewing subscriptions in CP

### ISSUE THREAD

**Issue by whoisgina** [digital-pros/commerce-authorize#30]
**Describe the bug**
When trying to view a subscription in the CP, there's an error re: a missing controller in the Authorize.net SDK:
`Error: Class "net\authorize\api\contract\v1\GetTransactionListForCustomerResponse" not found in /var/www/html/vendor/authorizenet/authorizenet/lib/net/authorize/api/controller/base/ApiOperationBase.php:150`.

**To Reproduce**
1. View subscriptions in Craft Commerce (`/admin/commerce/subscriptions?source=*`)
2. Click on a subscription
3. See error

**Expected behavior**
View and manage the subscription.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.1
 - Browser: Firefox
 - Version: 110.0

**Additional context**
This is an issue in the PHP SDK for Authorize.net and not in this plugin, but I'm not sure what the best practice would be here. I am able to fix the issue by changing the name of the class on line 11 in `authorizenet/authorizenet/lib/net/authorize/api/controller/GetTransactionListForCustomerController.php` from `GetTransactionListForCustomerResponse` to `GetTransactionListResponse`, per [this open issue](https://github.com/AuthorizeNet/sdk-php/issues/417). 

Right now I'm still testing this plugin, so I can change this locally, but once I move to a staging/production environment I'm imagining a not-so-great solution where I have to fork both the SDK and this plugin (not sure if the license allows for this), as I'll be doing automatic deploys and would prefer that Composer handles all the dependencies/versioning.

**Comment by benlobach** [comment]
Thanks for letting us know, @whoisgina! Given this is an SDK issue, we'll have to dig in, and see what's possible!

**Comment by whoisgina** [comment]
Whoa, you're quick! Let me know if I can provide any stack traces or screenshots to assist, thank you so much!

**Comment by benlobach** [comment]
@whoisgina - We have released version 4.0.2 which corrects this error, let us know if you run into any other issues!
