### ISSUE TITLE
Form field name collision when using `commerce/payments/pay` endpoint

### ISSUE THREAD

**Issue by justinholtweb** [digital-pros/commerce-authorize#31]
Our Commerce purchase flow uses `commerce/payments/pay` to accept payments on completed but unpaid orders. The Commerce endpoint requires a `number` param for retrieving the order based on the order number, but the markup for the Authorize.net payment form also uses `number` for the CC number, causing a collision.

**To Reproduce**
Hit a Commerce `commerce/payments/pay` endpoint, passing in the order number as a hidden param while also using the `cart.gateway.getPaymentFormHtml({})|raw ` shortcode with this plugin. 

**Expected behavior**
The Authorize.net plugin payment templates should be using a more terse handle for the payment form CC number field like `cc-number` to avoid collisions with Commerce requirements.

- Commerce 4.2.7
- Authorize.net for Craft Commerce 4.0.2

**Comment by benlobach** [comment]
Hey, @justinholtweb! Thanks for pointing this out! We'll take a look at adding an alternative option here.

**Comment by justinholtweb** [comment]
I was able to temporarily work around it by rendering the payment form markup manually field by field and using the field handles represented in your documentation. Would still be good to correct this on your embed template for other customers who may still prefer to render it.

**Comment by benlobach** [comment]
@justinholtweb - just wanted to let you know that the latest release (4.0.3) solves this problem when using the Accept.js option. As for the non-Accept.js users - the "number" field is a standard field on the CreditCard model, so we do have to leave it there for users who don't utilize the Accept.js functionality.

If you have questions, let us know! Thanks again for bringing this to our attention!

**Comment by justinholtweb** [comment]
Great thanks Ben!
