### ISSUE TITLE
"A duplicate transaction has been submitted." error after trying 2nd time payment where first time, cvv was wrong.

### ISSUE THREAD

**Issue by amici-infotech** [digital-pros/commerce-authorize#35]
Hello, We have installed a plugin into a site where client has tried to pay for a product and got `"This transaction has been declined."` error. Its obvious as CVV was wrong. 

After that, client has tried to pay again with correct CVV this time, but payment got Declined with error `"A duplicate transaction has been submitted."`.

In authorize.net support article, they've mentioned that in such cases duplicate transaction window is 2 minutes. however, client in our case tried payment within 50 seconds. Attaching screenshots of both transactions:

Time difference between 2 transactions are 50 seconds.
![image](https://github.com/digital-pros/commerce-authorize/assets/20450552/8911b089-43fa-4acd-900c-7b129b62ff25)

Transaction 1:
![image](https://github.com/digital-pros/commerce-authorize/assets/20450552/539986e7-913f-487f-8fe0-18f412db52d9)

Transaction 2:
![image](https://github.com/digital-pros/commerce-authorize/assets/20450552/8c2e10f1-c8b9-4d49-90df-1541efa84001)

On their [support page](https://support.authorize.net/knowledgebase/Knowledgearticle/?code=000001473), they mentioned that we can pass `x_duplicate_window` variable with transaction where we can change duplicate window time from 2 minutes to whatever we want. I would personally want that to change to 30 seconds. Is that possible with some sort of config settings right now inside the plugin? if not, can you add one? if it will take time, can you point us on right direction where we can make changes to achieve this on our end?

**Comment by benlobach** [comment]
@amici-infotech, thanks for submitting this ticket! One quick question as we investigate our options here, are you using Accept.js?

**Comment by amici-infotech** [comment]
This is my settings. I think YES!


![image](https://github.com/digital-pros/commerce-authorize/assets/20450552/87e079e0-07cc-4886-9299-bf258b610a63)

**Comment by benlobach** [comment]
@amici-infotech, thanks for confirming! 4.0.6 has just been released with support for Duplicate Window Timing. Let us know if you have questions!
