### ISSUE TITLE
Show saved credit cards on frontend

### ISSUE THREAD

**Issue by hassanmah** [digital-pros/commerce-authorize#38]
Hi,

Not a bug or issue, but can anyone point me to showing saved credit cards for the customer on the front end?

Thanks

**Comment by benlobach** [comment]
@hassanmah - Great to hear from you!

Looking at the sample code in the Craft Commerce repository, you should be able to use the following lookup and loop, hope this helps!

`
{% set paymentSources = craft.commerce.paymentSources.getAllPaymentSourcesByCustomerId(currentUser.id ?? null) %}

{% for source in paymentSources %}
    <label class="block cursor-pointer mt-3 [[classes.box.selection]]">
      <span class="flex justify-start items-center">
        <span class="pr-3">
          {{ input('radio', 'paymentSourceId', source.id, {
            checked: source.id == cart.paymentSourceId
          }) }}
        </span>
        <span>
          <strong>{{ source.description }}</strong>
          <br><span class="text-gray-600">{{ 'Stored source'|t }}</span>
        </span>
      </span>
    </label>
  {% endfor %}`

https://github.com/craftcms/commerce/blob/develop/example-templates/src/shop/checkout/payment-method.twig

**Comment by hassanmah** [comment]
@benlobach thanks for the quick reply that works well!

Can I piggyback on your answer and ask how would I go about allowing the user to add a payment card from a "manage my account" section, would this work? https://craftcms.com/docs/commerce/4.x/saving-payment-sources.html

Sort of like this screenshot

<img width="1334" alt="image" src="https://github.com/digital-pros/commerce-authorize/assets/3025707/3b9be828-6ea4-4173-a629-c5d95a8262a8">

Thanks again

**Comment by benlobach** [comment]
@hassanmah, yes, you should be able to create the payment source by following those instructions. If you run into problem, let me know!
