### ISSUE TITLE
Add ability to send tax amount with transaction

### ISSUE THREAD

**Issue by justinholtweb** [digital-pros/commerce-authorize#41]
**Is your feature request related to a problem? Please describe.**
Our merchant email that Authorize.net sends to the client when a purchase is made has fields for Tax under Additional Information. Our client would like to be able to see any taxes that are part of the purchase transactions in this email if possible.

**Describe the solution you'd like**
Have the ability to pass the tax amount from Commerce cart to Authorize.net to include in the merchant email and any other records Authorize.net has for the transactions.

**Describe alternatives you've considered**
None. 

**Additional context**
![Screen Shot 2024-01-18 at 11 17 22 AM](https://github.com/digital-pros/commerce-authorize/assets/295903/e27ff7d9-56da-46aa-a11b-dbf86391f44f)

**Comment by benlobach** [comment]
@justinholtweb - it's great to hear from you! After digging into the Authorize.net Omnipay gateway, it doesn't appear that the Omnipay driver allows us to specify the tax amount (or any other Level 2 data) within Authorize.net.
