### ISSUE TITLE
Struggling to get Subscription to work with saved payment source.

### ISSUE THREAD

**Issue by tdefilippis** [digital-pros/commerce-authorize#42]
**Describe the bug**
I receive this error when trying to subscribe with saved payment source in authorize.net sandbox account.

```
net\authorize\api\contract\v1\ARBCreateSubscriptionResponse {#1014 ▼
  -refId: "ref1707436028"
  -messages: net\authorize\api\contract\v1\MessagesType {#1016 ▼
    -resultCode: "Error"
    -message: array:1 [▼
      0 => net\authorize\api\contract\v1\MessagesType\MessageAType {#1015 ▼
        -code: "E00029"
        -text: "Payment information is required."
      }
    ]
  }
  -sessionToken: null
  -subscriptionId: null
  -profile: null
}
```

Here is the form that I am using:

```
{% extends 'site/wrapper' %}

{% block main %}
{% set plans = craft.commerce.getPlans().getAllPlans() %}

{% for plan in plans %}
  <form method="post">
    {{ csrfInput() }}
    {{ actionInput('commerce/subscriptions/subscribe') }}
    {{ hiddenInput('planUid', plan.uid|hash) }}

    <h4>{{ plan.name }}</h4>

    {% set paymentSources = craft.commerce.
      getPaymentSources().
      getAllGatewayPaymentSourcesByCustomerId(
        plan.getGateway().id,
        currentUser.id ?? null
      )
    %}

    {# If we don’t have a saved payment soruce, collect details for the gateway #}
    {% if not paymentSources|length %}
      <div class="paymentForm">
        {% namespace plan.getGateway().handle|commercePaymentFormNamespace %}
          {{ plan.getGateway().getPaymentFormHtml({})|raw }}
        {% endnamespace %}
      </div>
    {% endif %}

    <button>{{ "Subscribe"|t }}</button>
  </form>
{% endfor %}
{% endblock %}
```

Any idea what I am doing wrong?

Also, I would like to ask what the process for a first time subscriber is? do you first have to save their payment information using accept.js, and then subscribe? From the subscribe gateway method, it appears that it requires a saved payment source.

Is it possible to outline a subscription example in the documentation? The standard craft cms subscriptions documentation https://craftcms.com/docs/commerce/4.x/subscription-templates.html seems to allow for inputting credit cards directly in the subscription form, although it does state that it can vary based off of the gateway.

When I looked at vendor/digital-pros/commerce-authorize/src/gateways/Subscriptions.php, I noticed that there is an unused variable $paymentSource in the subscribe function: 
`$paymentSource = $this->getAllPaymentSources($user->id, $this->paymentSource);`

When I dumped this value, I got the payment source. However, when I dumped `$this->paymentSource`, it was null. But $this->paymentSource is the only variable used below to send payment details to authorize. Any clue how this logic works and what I am missing?

**Desktop (please complete the following information):**
 - OS: ios
 - Browser chrome
 - Version 121.0.6167.85

**Authorize Plugin Version
- 4.0.6

**Craft cms version
-4.7.2.1

**Additional context**

**Comment by benlobach** [comment]
@tdefilippis, what version of Craft Commerce are you running?

**Comment by tdefilippis** [comment]
I am using version 4.7.2.1

**Comment by benlobach** [comment]
Thanks for verifying your version number! Some of the Craft Commerce code has changed around this functionality. We'll have to run some tests, thanks for your patience!

**Comment by thomasdefilippis** [comment]
@benlobach I was able to get the subscription working with a slight code change. I made a pull request with explanation:

https://github.com/digital-pros/commerce-authorize/pull/43

**Comment by thomasdefilippis** [comment]
@benlobach did you notice this change log

https://github.com/craftcms/commerce/blob/develop/CHANGELOG.md#430---2023-09-13

Deprecated payment source creation via the commerce/subscriptions/subscribe action.

looks like best practice to create payment source before calling subscribe action.

**Comment by benlobach** [comment]
@thomasdefilippis - Yes, we plan on moving in this direction introduced in version 4, but some larger subscription changes are looming, so we are contemplating making these particular changes. Given that you still do not see the payment method, which means the depreciated function may not be working, we may have to go ahead and make those changes, but we'll need to run some additional testing on our end.

**Comment by thomasdefilippis** [comment]
Not sure, I understand your comment 

> Given that you still do not see the payment method

When I make the change referenced in the pull request, I can create a subscription with a saved payment source. 

More testing makes sense. Just glad to know you guys are continuing to maintain the plugin. Let me know if I can help, as I have a client who will likely use this plugin for a long period of time. 

Thanks,
Thomas Defilippis

**Comment by benlobach** [comment]
There's a legacy (depreciated) catch in Craft Commerce Core that creates the payment method if there's no payment method ID assigned so that it can all happen in one step, but it hasn't been working correctly. We thought it was corrected, but given that you're having trouble with it, we probably need to move to the two-step process.

**Comment by thomasdefilippis** [comment]
I see. This makes more sense. Thanks for the explanation.

**Comment by benlobach** [comment]
Hey, @tdefilippis! Just checking in to see if this has been resolved for you?
