### ISSUE TITLE
Craft 5 Compatible

### ISSUE THREAD

**Issue by AntoineLeeroy** [digital-pros/commerce-authorize#44]
**Is your feature request related to a problem? Please describe.**
Will this plugin be compatible with Craft 5 & Craft Commerce 5?

**Describe the solution you'd like**
Be compatible with Craft/Commerce 5 :)

**Describe alternatives you've considered**
We are currently considering using this plugin instead of doing a custom Gateway, but we are also considering doing our project in Craft 5.

**Comment by benlobach** [comment]
Hey, @AntoineLeeroy! It's great to hear from you. Craft 5 Compatibility is currently planned, but it won't be started until after Commerce 5 has released a stable version, as we're waiting to determine the next steps for subscriptions.
