### ISSUE TITLE
Craft 5 version ETA

### ISSUE THREAD

**Issue by justinholtweb** [digital-pros/commerce-authorize#46]
Hey folks, just checking if you have an ETA on a Craft 5 version? I know its early so no rush just doing some planning.

**Comment by benlobach** [comment]
Craft 5 Compatibility is currently planned, but it won't be started until after Commerce 5 has released a stable version, as we're waiting to determine the next steps for subscriptions.

**Comment by justinholtweb** [comment]
Glad to see you reopened this. Eager to hear any updates or ETA you have. Thank you for your work on this plugin!

**Comment by benlobach** [comment]
@justinholtweb—We're working on some final subscription changes in v4. As soon as those are resolved, we'll begin working upgrading for version 5. We want to be sure we have a stable version in v4 before making the jump. We don't have a specific timeline, but this compatibility upgrade is a high priority for our team.

**Comment by benlobach** [comment]
@justinholtweb - Version 5 has been released, let us know if you run into any hiccups!
