### ISSUE TITLE
Craft Commerce 5 compatibility 

### ISSUE THREAD

**Issue by mgambella** [digital-pros/commerce-authorize#47]
With Craft Commerce 5 released, I wanted to check if this is going to be updated for the new version.

**Comment by benlobach** [comment]
Closing this ticket as it's a duplicate of #46, and we'll update the status there as we work toward Craft Commerce 5 compatibility.

**Comment by benlobach** [comment]
@mgambella - Version 5 has been released, let us know if you run into any hiccups!
