### ISSUE TITLE
Allow developerMode to be set from an env var

### ISSUE THREAD

**Issue by elivz** [digital-pros/commerce-authorize#48]
Now that `gateway-settings.php` is deprecated, it would be reaaaalllly great to be able to define the `developerMode` settings in an environmental variable. Right now there (to my knowledge) no supported way to have the same codebase running in both test & production environments.

Even setting that value manually to something like `developerMode: $AUTHORIZE_NET_DEVELOPER_MODE` in the gateway config yaml file doesn't work, because that [setting isn't parsed](https://github.com/digital-pros/commerce-authorize/blob/f7e5dc31121d40455451f0a9dae172cfcf95a5b6/src/gateways/Gateway.php#L296).

Is there some other workaround that I'm missing?

**Comment by benlobach** [comment]
@elivz - Thanks for bringing this to our attention! We’ll take a look along with some of the changes we’re currently making for Craft Commerce 4.

**Comment by benlobach** [comment]
@elivz, this rolled out with version 4.0.7 today!
