### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by keyurshah** [digital-pros/commerce-authorize#5]
Hi there!

I'd like to use environment variables to allow different settings for dev and production.

I tried to use the $ method as described [here ](https://docs.craftcms.com/v3/config/environments.html#control-panel-settings) but when I type the dollar sign, the environmental variables dropdown does not appear

![image](https://user-images.githubusercontent.com/744385/63212415-21cbd500-c0b9-11e9-9101-06ea99817161.png)

perhaps in the future, another option would be to use a config file like I can with Blitz.

Thanks!

**Comment by benlobach** [comment]
@keyurshah, environment variables haven't been enabled for this gateway yet, but we're currently working on it. We should have a release with this functionality by the end of the week.

**Comment by keyurshah** [comment]
good to hear!

**Comment by sjcallender** [comment]
@benlobach Any updates on this feature? We're migrating a site this month and would value this update.

**Comment by benlobach** [comment]
@sjcallender, @keyurshah -- 

Thanks for checking in! We released a new version this evening that has support for Environment Variables. You can now set the API Key, Transaction Key, and Public Client Key with these variables.

If you would like to change the other fields, we have placed a [sample file](https://github.com/digital-pros/commerce-authorize/blob/master/commerce-gateways-sample.php) in the repository. You will need to rename the file (commerce-gateways.php), and place it in the config directory to overwrite the database settings. You will also want to update the handle in the file with the handle that's generated when you create the gateway inside Craft Commerce.

Let me know if you have any questions!

**Comment by keyurshah** [comment]
Thanks for the update with the environment variables.

I'm trying it out with the config file and something seems off.  I have my config (commerce-gateways.php file) getting values from .env

i.e.
`		'apiLoginId' => getenv('AUTHORIZE_NET_API_LOGIN_KEY'),`

It is then populating the exact value inside the form for the api values.  (by the way, in other plugins I've seen it give a little notice that the value is coming from the config file) 

And then, it is adding the exact api values in the project.yaml file.   so project.yaml still has the values being stored inside it. 

Thanks!

**Comment by benlobach** [comment]
@keyurshah,

Can you try populating the 'apiLoginId' with a value of '$AUTHORIZE_NET_API_LOGIN_KEY'?

Here's an example:
`'apiLoginId' => '$AUTHORIZE_NET_API_LOGIN_KEY',`

It looks like it's working here in my local environment, let me know if that works for you!

**Comment by benlobach** [comment]
One other thing to note -- you can take the API keys out of the commerce-gateways.php file, and reference the Environment Variables in the Gateway settings inside Craft Commerce. The commerce-gateways.php file only overwrites the values that are present in the file.

**Comment by keyurshah** [comment]
sorry for the delay. that seems to have work, by using 
```
'apiLoginId' => '$AUTHORIZE_NET_API_LOGIN_KEY',
```

thanks so much!

**Comment by keyurshah** [comment]
Hello,

Sorry, but this issue still seems to persist. I was just about to launch my production store, and couldn't submit payment.

It looks like it is staying in developer mode based on the js files being loaded

I checked project.yaml and it shows the following for settings

```
      settings:
        acceptJS: true
        apiLoginId: $AUTHORIZE_NET_API_LOGIN_KEY
        developerMode: false
        disableAcceptData: true
        insertForm: false
        paymentButton: 'Complete Order'
        publicKey: $AUTHORIZE_NET_API_PUBLIC_CLIENT_KEY
        savePaymentMethods: true
        savedCardPrefix: 'Saved Card - x'
        transactionKey: $AUTHORIZE_NET_API_TRANSACTION_KEY
        voidRefunds: true
```

I tried setting developerMode in my config file to

```
'developerMode' => getenv('AUTHORIZE_NET_DEVELOPER_MODE'),
```

with `AUTHORIZE_NET_DEVELOPER_MODE` set to true in `dev` and set to false in `production`

but production is still acting as if I am in dev mode.  Is there an environment variable lookup for developerMode similar to the api keys? Maybe that's the issue.

I can probably change it manually in the settings to not be in `dev` mode but it would be great if it can be dynamic so I don't have to change every time.

Thanks

**Comment by benlobach** [comment]
@keyurshah, Craft Commerce sets the gateway settings a bit differently than regular plugins. If you wish to set your gateway configuration programmatically for fields other than the keys (which use environment variables), you will need to use the commerce-gateways.php file in your config folder.

https://docs.craftcms.com/commerce/v3/payment-gateways.html#other-gateway-specifics 

There's a sample file that's available in the repo [here](https://github.com/digital-pros/commerce-authorize/blob/master/commerce-gateways-sample.php). Keep in mind that there's not an indicator available when these settings are overwritten from the file, your changes simply won't save if you change them in the Gateway settings area.

**Comment by benlobach** [comment]
Are you using the commerce-gateways.php file to set these configuration options?

**Comment by keyurshah** [comment]
Yes I’m using the commerce-gateways example provided. 

I tried using multi environment as well inside the config but that didn’t seem to work either. In order to set dev to false for test mode

It’s a bit confusing with the different combinations

Basically i need:

Production
- specific api keys
- test mode off

Dev
- specific api keys
- test mode on

Other settings are the same between them (acceptjs, etc)

Thanks

**Comment by keyurshah** [comment]
I should add that the key values would need to come from .env files for security.

thank you.

**Comment by keyurshah** [comment]
after playing around with this over the weekend, I was able to get it working. Here are some notes

* when creating a gateway, handle should be different than any before because older gateways are archived and not deleted. seemed like this could cause an issue when pulling data. I was seeing setting values from a previous gateway that had the same handle.
* when creating a gateway,
  * only set payment capture type (i.e. authorize) because it does not seem possible to change this from the config file
  * everything else, keep it blank
* do not open up gateway settings and save after the first time. This will populate from the .env file and will save actual the values to project.yaml


So if the possible issues could be checked for the future. It seems these might be Craft Commerce issues and not with this plugin.

* Avoid saving values from .env to be saved to project.yaml when the settings file is loaded and saved after first creation of the payment method.
* Allow payment capture type (authorize, authorize & capture) to be modified from the config file

thanks!

**Comment by benlobach** [comment]
@keyurshah, this is great, thanks so much!
