### ISSUE TITLE
Deprecated Config Override File

### ISSUE THREAD

**Issue by mike-moreau** [digital-pros/commerce-authorize#51]
Hey there, folks. I saw form this thread that it is possible to config commerce-authorize with a config file https://github.com/digital-pros/commerce-authorize/issues/18

When doing this in Craft 4.10.6 I get the following deprecation warning in the control panel.

`Overriding gateway settings using the commerce-gateways.php file has been deprecated. Use the gateway’s config file instead.`

Is it possible to use a config file as described in the Commerce docs here https://craftcms.com/docs/commerce/4.x/payment-gateways.html#storing-config-outside-of-the-database

That would be `config/commerce-authorize.php` correct?

**Comment by mike-moreau** [comment]
@benlobach when it's convenient could you follow up on the correct way to set up the config file? Thanks!

**Comment by benlobach** [comment]
@mike-moreau, my apologies for the delayed response! 

Most of the environment-specific settings can now be set with environment variables. Is there something that you'd like to set outside of those parameters?

**Comment by mike-moreau** [comment]
Thanks for the reply @benlobach. Yes, we prefer to have all configuration in config files where possible.

I understand we can use environment variables for most settings, but other such as lightswitch fields we could not.

We can use the `commerce-gateways.php` config file like [the example in this repo](https://github.com/digital-pros/commerce-authorize/blob/master/commerce-gateways-sample.php). But this approach is deprecated now.

Does the authorize gateway support a `commerce-authorize.php` config file?

Here are some related links:
- https://github.com/craftcms/commerce/issues/2101
- https://craftcms.com/docs/commerce/4.x/payment-gateways.html#storing-config-outside-of-the-database

**Comment by benlobach** [comment]
That makes sense! We'll have to do some investigating to see what's possible with the current configuration. 

Would you mind sharing which lightswitch fields in particular you'd like to change between your environments?

**Comment by benlobach** [comment]
Thanks, Mike! We investigated a solution here, but there are some complications with the gateway setup. It appears that it may introduce breaking changes for legacy users since we'd have to move to a settings model, and the changes would introduce problems for customers with multiple gateways (as the settings affect all gateways).

For now, we're planning to let that feature depreciate, but if you have a specific use case where you need an environment variable, we're happy to try to move that specific field to an environment variable.

**Comment by mike-moreau** [comment]
Understood, and thanks for looking into it.
