### ISSUE TITLE
Commerce 3 Compatibility Timeline

### ISSUE THREAD

**Issue by taylordaughtry** [digital-pros/commerce-authorize#6]
Hey! I'm currently working within a project that's going to launch with Commerce 3 (at some point in the future.) Are there any plans to update this package for Commerce 3 compatibility?

**Comment by benlobach** [comment]
Great question! Yes, we will be updating/testing the plugin for Commerce 3 compatibility. We'll begin testing once the Commerce team releases a beta version of Commerce 3.

**Comment by keyurshah** [comment]
looks like commerce 3.4 just launched woohoo!

tried to upgrade but got the error below

seems like the solution would be to add this to composer.json, but hopefully everything else would still work.

```
 "craftcms/commerce": "^2.1.0 || ^3.0.0",
```

error

```
Your requirements could not be resolved to an installable set of packages.

Problem 1
- digital-pros/commerce-authorize 1.0.8 requires craftcms/commerce ^2.0.0 -> satisfiable by craftcms/commerce[2.2.15, 2.2.14, 2.2.13, 2.2.12, 2.2.11, 2.2.10, 2.2.9, 2.2.8, 2.2.7, 2.2.6, 2.2.5, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.13, 2.1.12.1, 2.1.12, 2.1.11, 2.1.10, 2.1.9, 2.0.0-beta.1, 2.0.0-beta.1.1, 2.0.0-beta.1.2, 2.0.0-beta.2, 2.0.0-beta.3, 2.0.0-beta.4, 2.0.0-beta.4.1, 2.0.0-beta.5, 2.0.0-beta.6, 2.0.0-beta.7, 2.0.0-beta.8, 2.0.0-beta.8.1, 2.0.0-beta.9, 2.0.0-beta.10, 2.0.0-beta.11, 2.0.0-beta.12, 2.0.0-beta.12.1, 2.0.0-beta.13, 2.0.0-beta.13.1, 2.0.0-beta.14, 2.0.0-beta.15, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.0.1, 2.1.0.2, 2.1.1, 2.1.1.1, 2.1.2, 2.1.3, 2.1.3.1, 2.1.4, 2.1.5, 2.1.5.1, 2.1.5.2, 2.1.6, 2.1.6.1, 2.1.7, 2.1.8] but these conflict with your requirements or minimum-stability.
```

**Comment by taylordaughtry** [comment]
@benlobach Hey! In light of the GA release for 3, I wanted to check-in here and see how things were going with testing, and whether there was a timeline just yet on compatibility. We'd _really_ love to use this plugin!

Thanks for writing this plugin; it'd be a huge time-saver for us!

**Comment by benlobach** [comment]
We're currently testing our plugin with Craft Commerce 3. The gateway does appear to be working as expected from a front-end perspective, but we were unable to test an order all the way through due to a bug that the Craft team patched today. Once that fix is released, we'll run one more round of testing, and then create an official release for Commerce 3.

Our next area of focus will be back-end order testing, and we're hoping to have a release that covers that area within the next couple of weeks.

**Comment by benlobach** [comment]
Just a quick update - 1.0.9 has been released with Commerce 3 compatibility. If you need to process orders in the control panel, you will want to turn off the Accept.js toggle in the gateway settings until the next release.

If you run into anything as you test, please let us know!
