### ISSUE TITLE
Echeck

### ISSUE THREAD

**Issue by sm-md-lg** [digital-pros/commerce-authorize#8]
Does the authorize.net payment gateway support eCheck?  If not do you have any plans to in the future?

Here's info about it: https://developer.authorize.net/api/reference/features/echeck.html

**Comment by benlobach** [comment]
Hello, @sm-md-lg, it doesn't look like this is supported in the Authorize.net Omnipay gateway, and we don't have plans to write a manual integration around the gateway at this point.  

https://github.com/thephpleague/omnipay-authorizenet/issues/7 

We're going to close this issue, but if there's additional interest in this feature, feel free to drop us a note at hello@digitalpros.co!
